// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAic0RXqTTd_nPLyLLAuVgD8ihwTZn2mQs',
    appId: '1:310366778094:web:b58fa4c30a85f5ae88f9ff',
    messagingSenderId: '310366778094',
    projectId: 'justbite-bf0f5',
    authDomain: 'justbite-bf0f5.firebaseapp.com',
    storageBucket: 'justbite-bf0f5.firebasestorage.app',
    measurementId: 'G-EZRG3XNSLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIccBh5kjT4LQu5RgNCpTEwkKC-SjMNoM',
    appId: '1:310366778094:android:0e4f039d37cff71288f9ff',
    messagingSenderId: '310366778094',
    projectId: 'justbite-bf0f5',
    storageBucket: 'justbite-bf0f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwCoXkhySxMEiSOHesvYXmscvlbGLhGyo',
    appId: '1:310366778094:ios:0fc71e92f386f3d788f9ff',
    messagingSenderId: '310366778094',
    projectId: 'justbite-bf0f5',
    storageBucket: 'justbite-bf0f5.firebasestorage.app',
    iosBundleId: 'com.example.justbiteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwCoXkhySxMEiSOHesvYXmscvlbGLhGyo',
    appId: '1:310366778094:ios:0fc71e92f386f3d788f9ff',
    messagingSenderId: '310366778094',
    projectId: 'justbite-bf0f5',
    storageBucket: 'justbite-bf0f5.firebasestorage.app',
    iosBundleId: 'com.example.justbiteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAic0RXqTTd_nPLyLLAuVgD8ihwTZn2mQs',
    appId: '1:310366778094:web:57c6fe865077320a88f9ff',
    messagingSenderId: '310366778094',
    projectId: 'justbite-bf0f5',
    authDomain: 'justbite-bf0f5.firebaseapp.com',
    storageBucket: 'justbite-bf0f5.firebasestorage.app',
    measurementId: 'G-7HD1J1XR7S',
  );
}
